# Generated by Django 4.1.3 on 2023-02-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagenes.categoria'),
        ),
    ]
